# Generated by Django 5.0.3 on 2024-03-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=50)),
                ('student_school', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=50)),
            ],
        ),
    ]
