# Generated by Django 5.0.3 on 2024-04-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_school',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='user_id',
        ),
    ]
