# Generated by Django 5.0.3 on 2024-05-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_student_class_student_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
