# Generated by Django 5.0.3 on 2024-05-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_student_id_alter_student_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='users',
        ),
    ]
